### PR TITLE
Restrict element type of activation overrides to CUDNN datatypes

### LINKED ISSUE #47: Unconstrained element type on activations causing errors with e.g. Complex, ForwardDiff.Dual
Currently there doesn't appear to be any type constraints on the element type for the activation function overrides. This causes errors when non-CUDNN types (e.g. Complex, ForwardDiff.Dual) are passed in. Further, this breaks code that works before `using NNlibCUDA`, e.g.
```julia
using CUDA
x = CuArray([1.0 + 1.0im, 2.0 + 2.0im])
tanh.(x)
```
outputs
```julia
2-element CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}:
 1.0839233273386943 + 0.27175258531951174im
 1.0238355945704727 - 0.028392952868232284im
```
but when immediately followed by
```julia
using NNlibCUDA
tanh.(x)
```
we get
```julia
ERROR: MethodError: no method matching cudnnDataType(::Type{ComplexF64})
Closest candidates are:
  cudnnDataType(::Type{Float16}) at C:\Users\domin\.julia\packages\CUDA\qAl31\lib\cudnn\util.jl:7
  cudnnDataType(::Type{Float32}) at C:\Users\domin\.julia\packages\CUDA\qAl31\lib\cudnn\util.jl:8
  cudnnDataType(::Type{Float64}) at C:\Users\domin\.julia\packages\CUDA\qAl31\lib\cudnn\util.jl:9
  ...
Stacktrace:
 [1] CUDA.CUDNN.cudnnTensorDescriptor(array::CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}; format::CUDA.CUDNN.cudnnTensorFormat_t, dims::Vector{Int32})
   @ CUDA.CUDNN C:\Users\domin\.julia\packages\CUDA\qAl31\lib\cudnn\tensor.jl:9
 [2] CUDA.CUDNN.cudnnTensorDescriptor(array::CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer})
   @ CUDA.CUDNN C:\Users\domin\.julia\packages\CUDA\qAl31\lib\cudnn\tensor.jl:8
 [3] cudnnActivationForward!(y::CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}, x::CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}; o::Base.Iterators.Pairs{Symbol, CUDA.CUDNN.cudnnActivationMode_t, Tuple{Symbol}, NamedTuple{(:mode,), Tuple{CUDA.CUDNN.cudnnActivationMode_t}}})
   @ CUDA.CUDNN C:\Users\domin\.julia\packages\CUDA\qAl31\lib\cudnn\activation.jl:22
 [4] (::NNlibCUDA.var"#74#78")(src::CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}, dst::CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer})
   @ NNlibCUDA C:\Users\domin\.julia\packages\NNlibCUDA\i1IW9\src\cudnn\activations.jl:10
 [5] materialize(bc::Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{1}, Nothing, typeof(tanh), Tuple{CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}}})
   @ NNlibCUDA C:\Users\domin\.julia\packages\NNlibCUDA\i1IW9\src\cudnn\activations.jl:30
```

Is there an easy way to add some type constraints to this code to make sure its only applied to CUDNN types? E.g. would changing
```julia
function Base.materialize!(dst::DenseCuArray{<:CUDNNFloat},
                                   bc::Broadcast.Broadcasted{<:Any,<:Any,typeof($f),<:Tuple{DenseCuArray}})
...
function Base.materialize(bc::Broadcast.Broadcasted{<:Any,<:Any,typeof($f),<:Tuple{DenseCuArray}})
...
```
to
```julia
function Base.materialize!(dst::DenseCuArray{<:CUDNNFloat},
                                   bc::Broadcast.Broadcasted{<:Any,<:Any,typeof($f),<:Tuple{DenseCuArray{<:CUDNNNFloat}}})
...
function Base.materialize(bc::Broadcast.Broadcasted{<:Any,<:Any,typeof($f),<:Tuple{DenseCuArray{<:CUDNNFloat}}})
...
```
suffice? I'm not too familiar with using @eval.

### PR DESCRIPTION
**Pull request by DomCRose**
Fixes #47. 

I'm not managing to run the full testset locally with a rather unclear error, however, running the activations test file manually passes. Hopefully CI also passes.

Along with adding a test for tanh with complex numbers (but no others, as I'm unsure whether they will work with complex inputs), I've also expanded the ForwardDiff.Dual testset to cover the activations affected by NNlibCUDA.

I also did a little crude test on my end to check it still used the activation overrides for floats (putting a print line inside the function and running code which should hit it, removed from the PR of course).

### CODE REVIEW

File: test/activations.jl [hunk 1]
```diff
@@ -7,9 +7,27 @@
...
+    @test f(ds) ≈ collect(f(CuArray(ds)))
+    f = (x) -> σ.(x)
+    ds = Dual.(rand(5),1)
+    @test f(ds) ≈ collect(f(CuArray(ds)))
+    f = (x) -> elu.(x)
+    ds = Dual.(rand(5),1)
+    @test f(ds) ≈ collect(f(CuArray(ds)))
+    f = (x) -> relu.(x)
+    ds = Dual.(rand(5),1)
+    @test f(ds) ≈ collect(f(CuArray(ds)))
```
Comment (ToucheSir) [inline test/activations.jl:24]: I would drop the anonymous function entirely and turn this into a loop over activation functions.

File: test/activations.jl [hunk 2]
```diff
@@ -7,9 +7,27 @@
...
+end
+
+@testset "complex" begin
+    f = (x) -> tanh.(x)
```
Comment (ToucheSir) [inline test/activations.jl:28]:
```suggestion
    f(x) = tanh.(x)
```

Comment (ToucheSir) [reply test/activations.jl:28]: A comment mentioning why this test exists would be good too. e.g. broadcasting over a complex CuArray should work without NNlibCUDA, but this ensures that NNlibCUDA doesn't accidentally make this take a fast path that doesn't support complex numbers.

**Review by ToucheSir — CHANGES_REQUESTED** [review]

File: test/activations.jl (hunk 2 above)
Comment (DomCRose) [reply test/activations.jl]: I've added the comment, thanks!

File: test/activations.jl (hunk 1 above)
Comment (DomCRose) [reply test/activations.jl]: I've copied the activation broadcast test syntax (although I don't entirely understand the need for the @eval and interpolation), so the Dual tests now cover all activations accept rrelu (which I'm guessing doesn't work on gpu?).

Could it be worth adding similar tests to NNlib itself? I noticed it lacked any Dual number tests.

Comment (ToucheSir) [reply test/activations.jl]: `@eval` is needed because `NNlib.ACTIVATIONS` is an [array of symbols](https://github.com/FluxML/NNlib.jl/blob/ff3ac6eb807e9b41f46f28f8b3287d19f4b722c7/src/activations.jl#L6-L12). As for `rrelu`, it appears to be excluded because it is [non-deterministic](https://github.com/FluxML/NNlib.jl/blob/ff3ac6eb807e9b41f46f28f8b3287d19f4b722c7/src/activations.jl#L260).

**Review by ToucheSir — APPROVED** [review]
Thanks!
